import { z } from 'zod';

export const pageLayoutEnum = z.enum(['list', 'detail', 'dashboard', 'settings']);
export const pageComponentEnum = z.enum(['table', 'form', 'chart', 'card']);

export const PageSchema = z.object({
  name: z.string(),
  route: z.string(),
  layout: pageLayoutEnum,
  boundEntity: z.string().optional(),
  components: z.array(pageComponentEnum)
});

export const apiMethodEnum = z.enum(['GET', 'POST', 'PUT', 'DELETE']);

export const ApiEndpointSchema = z.object({
  path: z.string(),
  method: apiMethodEnum,
  handlerDescription: z.string().optional().default(''),
  boundEntity: z.string(),
  authRequired: z.boolean().optional().default(true),
  rateLimited: z.boolean().optional().default(false)
});

// Open string instead of enum — allows any role name generated by the AI (admin, manager, sales_rep, author, etc.)
export const rbacRoleEnum = z.string();

export const PermissionMatrixSchema = z.object({
  read: z.boolean().optional().default(false),
  write: z.boolean().optional().default(false),
  delete: z.boolean().optional().default(false)
});

export const AuthRuleSchema = z.object({
  role: z.string(),
  entity: z.string(),
  permissions: PermissionMatrixSchema
});

export const supportedIntegrationEnum = z.string();

export const triggerEventEnum = z.enum(['created', 'updated', 'deleted', 'status_changed']);

export const IntegrationHookSchema = z.object({
  integrationId: supportedIntegrationEnum,
  triggerEntity: z.string(),
  triggerEvent: triggerEventEnum,
  action: z.string()
});

export const TriggerSchema = z.object({
  entity: z.string(),
  event: triggerEventEnum,
  condition: z.string().optional().default('')
});

export const WorkflowStubSchema = z.object({
  name: z.string(),
  trigger: TriggerSchema,
  integration: supportedIntegrationEnum,
  action: z.string(),
  payload: z.record(z.string(), z.any())
});

export const AppSpecDef = z.object({
  roles: z.array(z.string()).optional().default([]),
  pages: z.array(PageSchema).optional().default([]),
  apiEndpoints: z.array(ApiEndpointSchema).optional().default([]),
  authRules: z.array(AuthRuleSchema).optional().default([]),
  integrationHooks: z.array(IntegrationHookSchema).optional().default([]),
  workflowStubs: z.array(WorkflowStubSchema).optional().default([])
});

export type Page = z.infer<typeof PageSchema>;
export type ApiEndpoint = z.infer<typeof ApiEndpointSchema>;
export type AuthRule = z.infer<typeof AuthRuleSchema>;
export type IntegrationHook = z.infer<typeof IntegrationHookSchema>;
export type WorkflowStub = z.infer<typeof WorkflowStubSchema>;
export type AppSpec = z.infer<typeof AppSpecDef>;
